TOP=../..

include $(TOP)/configure/CONFIG

LIBRARY_IOC += procServControl
DBD += procServControl.dbd
procServControl_SRCS += procServControl.st
procServControl_LIBS += $(EPICS_BASE_IOC_LIBS)

include $(TOP)/configure/RULES

